# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HkWMN0i9-8Yskv8nAdOyprhgM83kbjC
"""

import array as arr

import array as arr
a=arr.array('d',[1.9,2.8,3.5,4.9,5.7]);
for i in range(0,5):
    if(i==4):
        print(a[i],end=" ")
    else:
        print(a[i],end='::')

a.insert(2,10.9)

for i in (a):
    if(i==4):
        print(a[i],end=" ")
    else:
        print(a[i],end='::')

b=a[2:4]

for i in range(0,2):
    if(i==1):
        print(b[i],end=" ")
    else:
        print(b[i],end='::')

m="Hello"

print(m)

print(b)

def abc(num1:int,num2:int)->int:
  res=num1+num2
  return res

sum=abc(5,6)
print(sum)

